# Generated by Django 2.2.4 on 2019-08-24 14:08

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('image_path', models.ImageField(upload_to=backend.models.new_image_path)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('thumbnails_json', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
    ]
