# Generated by Django 2.2.4 on 2019-08-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemetadata',
            old_name='image_path',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='thumbnails_json',
            field=models.CharField(blank=True, default='[]', max_length=256, null=True),
        ),
    ]
