# Generated by Django 2.2.5 on 2019-10-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190826_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemetadata',
            name='filename',
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='thumbnails_json',
            field=models.CharField(default='[]', max_length=256),
        ),
    ]
