# Generated by Django 2.2.5 on 2019-10-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191010_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='year',
            field=models.CharField(max_length=256),
        ),
    ]
