# Generated by Django 2.2.5 on 2019-10-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191011_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootImage',
            fields=[
                ('image_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.ImageMetadata')),
            ],
        ),
        migrations.CreateModel(
            name='RootPath',
            fields=[
                ('image_path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.ImagePath')),
            ],
        ),
    ]
