# Generated by Django 2.2.5 on 2019-10-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rootimage_rootpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepath',
            name='path',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
