# Generated by Django 2.2.7 on 2019-12-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20191209_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagepath',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
