name: Fotogalleri - CI

on: pull_request

jobs:
  setup:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install virtualenv
        run: pip install virtualenv
  lint:
    runs-on: ubuntu-16.04
    needs: setup
    steps:
      # Without the following action the Makefile won't be found
      - uses: actions/checkout@v1
      - name: Lint with PEP8
        run:
          make test-pep8
  test:
    runs-on: ubuntu-16.04
    needs: setup
    steps:
      # Without the following action the Makefile won't be found
      - uses: actions/checkout@v1
      - name: Run tests
        run:
          make test

