name: Fotogalleri - CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.5.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.5.2
      - name: Lint with PEP8
        run:
          make test-pep8
      - name: Run tests
        run:
          make test
